name: sky_lists
description: A modern, real-time list app

version: 0.3+17

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1

  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1

  intl: ^0.16.0
  vibration: ^1.2.2
  validators: ^2.0.0+1
  random_color: ^1.0.3
  qr_flutter: ^3.2.0
  flutter_signin_button: ^1.0.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1
  url_launcher: ^5.4.1
  fast_qr_reader_view: ^0.1.5
  permission_handler: ^4.0.0
  soundpool: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
