name: sky_lists
description: A modern, real-time list app

version: 0.3+17

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.3
  firebase_ml_vision: ^0.9.3+5
  firebase_analytics: ^5.0.9
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.1
  google_fonts: ^0.3.2
  flutter_camera_ml_vision: ^2.2.4

  intl: ^0.16.0
  vibration: ^1.2.2
  validators: ^2.0.0+1
  random_color: ^1.0.3
  qr_flutter: ^3.2.0
  flutter_auth_buttons: ^0.6.0
  flutter_facebook_login: ^3.0.0
  url_launcher: ^5.4.1
  permission_handler: ^4.0.0
  soundpool: ^0.6.0
  get_version: ^0.2.0+1

  provider: ^4.0.1
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2

  list_metadata_repository:
    path: list_metadata_repository
  list_items_repository:
    path: list_items_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
